server:
  port: 8080
spring:
  datasource:
    ###可读数据源
    read:
      jdbc-url: jdbc:mysql://localhost:3306/datasource1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    ###可写数据源
    write:
      jdbc-url: jdbc:mysql://localhost:3306/datasource2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    type: com.alibaba.druid.pool.DruidDataSource